Rails.application.routes.draw do
  # resources :infos
  # resources :users
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope '/api/v1' do
    post 'users/login', to: 'user#login'
    post 'users/register', to: 'user#register'
    post 'users/refresh_token', to: 'user#refresh_token'
    get 'users', to: 'user#index'
    post 'users', to: 'user#create'    
    get 'users/myinfo', to: 'user#myinfo'
    get 'users/mentor/:mentor_id', to: 'user#apply_mentor'
    get 'users/:id', to: 'user#show'
    put 'users/myinfo', to: 'user#update_myinfo'
    put 'users/:id', to: 'user#update'
    delete 'users/:id', to: 'user#destroy'
    
    get 'user_tickets', to: 'user_ticket#index'
    get 'user_tickets/mine', to: 'user_ticket#my_tickets'
    get 'user_tickets/:id', to: 'user_ticket#show'
    get 'user_tickets/:id/allow', to: 'user_ticket#allow_purchase'
    post 'user_tickets/purchase', to: 'user_ticket#purchase'
    post 'user_tickets/:id/purchase', to: 'user_ticket#update_mentee_tickets'
    post 'user_tickets', to: 'user_ticket#create'
    put 'user_tickets/:id', to: 'user_ticket#update'
    delete 'user_tickets/:id', to: 'user_ticket#destroy'
    
    get 'purchase_histories', to: 'purchase_history#index'
    get 'purchase_histories/download', to: 'purchase_history#download_pdf'
    get 'purchase_histories/:id', to: 'purchase_history#show'
    post 'purchase_histories', to: 'purchase_history#create'
    put 'purchase_histories/:id', to: 'purchase_history#update'
    delete 'purchase_histories/:id', to: 'purchase_history#destroy'

    post 'admins/login', to: 'admin#login'
    post 'admins/register', to: 'admin#register'
    get 'admins', to: 'admin#index'
    get 'admins/:id', to: 'admin#show'
    put 'admins/:id', to: 'admin#update'
    delete 'admins/:id', to: 'admin#destroy'

    post 'mentors/login', to: 'mentor#login'
    post 'mentors/register', to: 'mentor#register'
    get 'mentors', to: 'mentor#index'
    get 'mentors_event', to: 'mentor#mentors_event'
    get 'mentors/:id', to: 'mentor#show'
    put 'mentors/:id', to: 'mentor#update'
    post 'mentors/salary_change', to: 'mentor#salary_change'
    delete 'mentors/:id', to: 'mentor#destroy'

    get 'plans', to: 'plan#index'
    get 'plans/:id', to: 'plan#show'
    post 'plans', to: 'plan#create'
    put 'plans/:id', to: 'plan#update'
    delete 'plans/:id', to: 'plan#destroy'

    get 'companies', to: 'company#index'
    get 'companies/:id', to: 'company#show'
    post 'companies', to: 'company#create'
    put 'companies/:id', to: 'company#update'
    delete 'companies/:id', to: 'company#destroy'
    
    get 'company_reviews', to: 'company_review#index'
    get 'company_reviews/:id', to: 'company_review#show'
    post 'company_reviews', to: 'company_review#create'
    put 'company_reviews/:id', to: 'company_review#update'
    delete 'company_reviews/:id', to: 'company_review#destroy'

    get 'job_categories', to: 'job_category#index'
    get 'job_categories/:id', to: 'job_category#show'
    post 'job_categories', to: 'job_category#create'
    put 'job_categories/:id', to: 'job_category#update'
    delete 'job_categories/:id', to: 'job_category#destroy'

    get 'industries', to: 'industry#index'
    get 'industries/:id', to: 'industry#show'
    post 'industries', to: 'industry#create'
    put 'industries/:id', to: 'industry#update'
    delete 'industries/:id', to: 'industry#destroy'

    get 'events', to: 'event#index'
    get 'events_calandar', to: 'event#events_calandar'
    get 'events3', to: 'event#events3'
    get 'myevents', to: 'event#myevents'
    get 'gelillas', to: 'event#gelillas'
    get 'events/reservable', to: 'event#reservable'
    get 'events/:id', to: 'event#show'
    post 'events', to: 'event#create'
    put 'events/:id', to: 'event#update'
    delete 'events/:id', to: 'event#destroy'
   

    get 'event_reservations', to: 'event_reservation#index'
    get 'event_reservations/user', to: 'event_reservation#user_reservations'
    get 'event_reservations/:id', to: 'event_reservation#show'
    post 'event_reservations', to: 'event_reservation#create'
    put 'event_reservations/:id', to: 'event_reservation#update'
    delete 'event_reservations/:id', to: 'event_reservation#destroy'
    
    get 'entry_sheets', to: 'entry_sheet#index'
    get 'entry_sheets/:id', to: 'entry_sheet#show'
    get 'entry_sheets_es3', to: 'entry_sheet#es3'
    get 'myes', to: 'entry_sheet#myes'
    post 'entry_sheets', to: 'entry_sheet#create'
    put 'entry_sheets/:id', to: 'entry_sheet#update'
    delete 'entry_sheets/:id', to: 'entry_sheet#destroy'

    get 'entry_sheet_comments', to: 'entry_sheet_comment#index'
    get 'entry_sheet_comments/:id', to: 'entry_sheet_comment#show'
    post 'entry_sheet_comments', to: 'entry_sheet_comment#create'
    put 'entry_sheet_comments/:id', to: 'entry_sheet_comment#update'
    delete 'entry_sheet_comments/:id', to: 'entry_sheet_comment#destroy'

    get 'entry_sheet_histories', to: 'entry_sheet_history#index'   
    get 'entry_sheet_histories/:id', to: 'entry_sheet_history#show'
    post 'entry_sheet_histories', to: 'entry_sheet_history#create'
    put 'entry_sheet_histories/:id', to: 'entry_sheet_history#update'
    delete 'entry_sheet_histories/:id', to: 'entry_sheet_history#destroy'
    
    get 'case_today', to: 'case_study#case_today'
    get 'case_studies/mycases', to: 'case_study#mycases'
    get 'case_studies/myeditcases', to: 'case_study#myeditcases'
    get 'case_studies/cases3', to: 'case_study#cases3'
    get 'case_studies/', to: 'case_study#index'
    get 'case_studies/:id', to: 'case_study#show'   
    post 'case_studies', to: 'case_study#create'
    put 'case_studies/:id', to: 'case_study#update'
    put 'case_studies/public/:id', to: 'case_study#public'
    delete 'case_studies/:id', to: 'case_study#destroy'
    
    get 'case_study_comments', to: 'case_study_comment#index'
    get 'case_study_comments/challenges', to: 'case_study_comment#challenges'
    get 'case_study_comments/:id', to: 'case_study_comment#show'
    post 'case_study_comments', to: 'case_study_comment#create'
    put 'case_study_comments/:id', to: 'case_study_comment#update'
    delete 'case_study_comments/:id', to: 'case_study_comment#destroy'

    get 'interview_reservations', to: 'interview_reservation#index'
    get 'interview_reservations/:id', to: 'interview_reservation#show'
    post 'interview_reservations', to: 'interview_reservation#create'
    put 'interview_reservations/:id', to: 'interview_reservation#update'
    delete 'interview_reservations/:id', to: 'interview_reservation#destroy'

    get 'event_reservations', to: 'event_reservation#index'
    get 'event_reservations/:id', to: 'event_reservation#show'
    post 'event_reservations', to: 'event_reservation#create'
    put 'event_reservations/:id', to: 'event_reservation#update'
    delete 'event_reservations/:id', to: 'event_reservation#destroy'

    get 'selection_statuses', to: 'selection_status#index'
    get 'selection_statuses/:id', to: 'selection_status#show'
    post 'selection_statuses', to: 'selection_status#create'
    put 'selection_statuses/:id', to: 'selection_status#update'
    delete 'selection_statuses/:id', to: 'selection_status#destroy'

    get 'interview_experiences', to: 'interview_experience#index'
    get 'interview_experiences/:id', to: 'interview_experience#show'
    post 'interview_experiences', to: 'interview_experience#create'
    put 'interview_experiences/:id', to: 'interview_experience#update'
    delete 'interview_experiences/:id', to: 'interview_experience#destroy'

    get 'articles', to: 'article#index'
    get 'articles/last', to: 'article#last_article'
    get 'articles/:id', to: 'article#show'
    post 'articles', to: 'article#create'
    put 'articles/:id', to: 'article#update'
    delete 'articles/:id', to: 'article#destroy'

    get 'zooms', to: 'zoom#index'
    get 'zooms/last', to: 'zoom#last_zoom'
    get 'zooms/:id', to: 'zoom#show'
    post 'zooms', to: 'zoom#create'
    put 'zooms/:id', to: 'zoom#update'
    delete 'zooms/:id', to: 'zoom#destroy'
    put 'zooms/public/:id', to: 'zoom#public'

    get 'files/*path', to: 'test#file_show'
  end
  root to: 'test#welcome'
end
